# Generated by Django 6.1.1 on 2026-10-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client'), ('Delivery-patner', 'Delivery_patner'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
